apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sqldata
spec:
  capacity:
    storage: 5G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  claimRef:
    namespace: default
    name: pvc-sqldata
  hostPath:
    path: /shared/sql-data
    type: ''