apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sqlmaster
spec:
  capacity:
    storage: 5G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  claimRef:
    namespace: default
    name: pvc-sqlmaster
  hostPath:
    path: /shared/sql-master
    type: ''