apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sqldata
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
  volumeName: pv-sqldata
  volumeMode: Filesystem