apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sqlmaster
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
  volumeName: pv-sqlmaster
  volumeMode: Filesystem