apiVersion: v1
kind: Service
metadata:
  name: azure-sql-server
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: azuresql
  ports:
    - name: tcp-port
      port: 1433
      targetPort: 1433
      protocol: TCP
